### ISSUE TITLE
Pre-trained Weights

### ISSUE THREAD

**Issue by ahmadmughees** [NJUVISION/AWnet#1]
Hi, 

Its an amazing work. please upload the pre-trained weights to play around with. Thanks.

**Comment by NJUVISION** [comment]
Ok, I have upload the pre-trained models in: http://yun.nju.edu.cn/d/b1d5b3c3a3/

**Comment by NJUVISION** [comment]
I have uploaded the pre-trained models in: http://yun.nju.edu.cn/d/b1d5b3c3a3/
